<div style="background: #000;
            color: #FFF;
            margin: 0px;
            padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1 >Week 18 Class 2 01/26</h1>
</div>

## Objectives for this week:
* Data Structuring 
* Data Cleanup

## Todays Agenda
* Continuing our code along
* Lab

<div style="background: #000;
            color: #FFF;
            margin: 0px;
            padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1 >Homework Problem</h1>
</div>

## Exercise 3

Given a stream of integers and a window size, calculate the moving average of all integers in the sliding window.

Implement the `MovingAverage` class:
* `MovingAverage(size)` Initializes the object with the size of the window size.
* `next(val)` Returns the moving average of the last size values of the stream.

**Example 1:** 
movingAverage = MovingAverage(3);  
movingAverage.next(1); // return 1.0 = 1 / 1  
movingAverage.next(10); // return 5.5 = (1 + 10) / 2  
movingAverage.next(3); // return 4.66667 = (1 + 10 + 3) / 3  
movingAverage.next(5); // return 6.0 = (10 + 3 + 5) / 3

In [1]:
class MovingAverage(object):
    def __init__(self, size):
        """
        Initialize your data structure here.
        :type size: int
        """
        self.max_size = size
        self.window = []
        

    def next(self, val):
        """
        :type val: int
        :rtype: float
        """
        if len(self.window) == self.max_size:
            self.window.pop(0)
        self.window.append(val)
        return sum(self.window)/len(self.window)  

moving_average = MovingAverage(3)
print(moving_average.next(1))# == 1.0
print(moving_average.next(10))# == 5.5
print(moving_average.next(3))# == 4.666666666666667
print(moving_average.next(5))# == 6.0

try:
    moving_average = MovingAverage(3)
    assert(moving_average.next(1) == 1.0)
    assert(moving_average.next(10) == 5.5)
    assert(moving_average.next(3) == 4.666666666666667)
    assert(moving_average.next(5) == 6.0)
    moving_average = MovingAverage(5)
    assert(moving_average.next(4) == 4.0)
    assert(moving_average.next(1) == 2.5)
    assert(moving_average.next(10) == 5.0)
    assert(moving_average.next(5) == 5.0)
    print("solution is correct")
except AssertionError:
    print("solution is incorrect")

1.0
5.5
4.666666666666667
6.0
solution is correct

In [2]:
from collections import deque

class MovingAverage(object):
    def __init__(self, size):
        """
        Initialize your data structure here.
        :type size: int
        """
        self.window = deque(maxlen=size)
        

    def next(self, val):
        """
        :type val: int
        :rtype: float
        """
        self.window.append(val)
        return sum(self.window)/len(self.window)  

try:
    moving_average = MovingAverage(3)
    assert(moving_average.next(1) == 1.0)
    assert(moving_average.next(10) == 5.5)
    assert(moving_average.next(3) == 4.666666666666667)
    assert(moving_average.next(5) == 6.0)
    moving_average = MovingAverage(5)
    assert(moving_average.next(4) == 4.0)
    assert(moving_average.next(1) == 2.5)
    assert(moving_average.next(10) == 5.0)
    assert(moving_average.next(5) == 5.0)
    print("solution is correct")
except AssertionError:
    print("solution is incorrect")

solution is correct

**[more on deque](https://docs.python.org/3/library/collections.html#collections.deque)**

<div style="background: #000;
            color: #FFF;
            margin: 0px;
            padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1>Books</h1>
</div>

Start here:
[Mathematics for Computer Science](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-042j-mathematics-for-computer-science-fall-2010/readings/MIT6_042JF10_notes.pdf)  
[Introduction to Probability](http://www.dartmouth.edu/~chance/teaching_aids/books_articles/probability_book/pdf.html)  
[Statistics](https://upload.wikimedia.org/wikipedia/commons/8/82/Statistics.pdf)  
[Think Stats (using python)](https://greenteapress.com/thinkstats2/thinkstats2.pdf)  
[Think Bayes](https://www.greenteapress.com/thinkbayes/thinkbayes.pdf)  
[Probabilistic Programming and Bayesian Methods for Hackers](https://nbviewer.jupyter.org/github/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter1_Introduction/Ch1_Introduction_PyMC3.ipynb)

<div style="background: #000;
            color: #FFF;
            margin: 0px;
            padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1>Code Along</h1>
    <h3>Cleaning up dirty data</h3>
</div>

Some new things we'll cover in this code along:

[pandas.DataFrame.apply](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html) - applies a function to rows of a col  
[pandas.DataFrame.drop](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html) - drops rows or columns  
[pandas.DataFrame.drop_duplicates](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) - drops duplicates  
[pandas.DataFrame.duplicated](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html) - returns True if duplicate  
[pandas.DataFrame.fillna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html) - fills NaN values  
[pandas.merge](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html) - merges two dfs

Importing the libraries we'll be using

In [3]:
import numpy as np 
import pandas as pd 
import datetime

Let's open the `ted_talks.csv` file and generate a dataframe. Then we'll check the top of the `df` to see what we have.

In [4]:
df = pd.read_csv("../datasets/ted_talks.csv")
df.head()

,ID,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
0,0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Emma Rob,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
1,1,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Emma Rob,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
2,2,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,43,NaN,Al Gore: Averting the climate crisis,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
3,3,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,26,NaN,David Pogue: Simplicity sells,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292
4,4,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,1140912000,35,Majora Carter,Majora Carter: Greening the ghetto,-1,1151367060,"[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550

Checking the shape of the `df`

In [5]:
df.shape

(2555, 18)

Checking info to see other information (like how much RAM our dataset uses and how many non-null entries we have)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2555 entries, 0 to 2554
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  2555 non-null   int64
 1   comments            2555 non-null   int64
 2   description         2555 non-null   object
 3   duration            2555 non-null   int64
 4   event               2555 non-null   object
 5   film_date           2555 non-null   int64
 6   languages           2555 non-null   int64
 7   main_speaker        2531 non-null   object
 8   name                2555 non-null   object
 9   num_speaker         2555 non-null   int64
 10  published_date      2555 non-null   int64
 11  ratings             2555 non-null   object
 12  related_talks       2555 non-null   object
 13  speaker_occupation  2549 non-null   object
 14  tags                2555 non-null   object
 15  title               2555 non-null   object
 16  url                 2555 non-null   object
 17  views               2555 non-null   int64
dtypes: int64(8), object(10)
memory usage: 359.4+ KB

We see we have 2555 rows but 2531 non-null rows for 'main_speaker'. So let's check that out.

In [7]:
df[df['main_speaker'].isna()][["description", "main_speaker","name"]]

,description,main_speaker,name
2,With the same humor and humanity he exuded in ...,NaN,Al Gore: Averting the climate crisis
3,New York Times columnist David Pogue takes aim...,NaN,David Pogue: Simplicity sells
13,Jehane Noujaim unveils her 2006 TED Prize wish...,NaN,Jehane Noujaim: My wish: A global day of film
34,Cambridge researcher Aubrey de Grey argues tha...,NaN,Aubrey de Grey: A roadmap to end aging
62,Writer and actor Anna Deavere Smith gives life...,NaN,Anna Deavere Smith: Four American characters
75,Graphic designer Stefan Sagmeister takes the a...,NaN,Stefan Sagmeister: Happiness by design
93,Green-minded architect and designer William Mc...,NaN,William McDonough: Cradle to cradle design
123,Alan Russell studies regenerative medicine -- ...,NaN,Alan Russell: The potential of regenerative me...
161,"Lawrence Lessig, the Net’s most celebrated law...",NaN,Lawrence Lessig: Laws that choke creativity
191,What if human consciousness isn't the end-all ...,NaN,Michael Pollan: A plant's-eye view
222,Novelist Amy Tan digs deep into the creative p...,NaN,Amy Tan: Where does creativity hide?
237,"Around the world right now, one billion people...",NaN,"Paul Collier: The ""bottom billion"""
249,Benjamin Zander has two infectious passions: c...,NaN,Benjamin Zander: The transformative power of c...
268,Chris Abani tells stories of people: People st...,NaN,Chris Abani: On humanity
282,"Imagine hearing great, departed pianists play ...",NaN,"John Q. Walker: Great piano performances, recr..."
318,Humorist John Hodgman rambles through a new st...,NaN,"John Hodgman: Aliens, love -- where are they?"
362,Reporter Jennifer 8. Lee talks about her hunt ...,NaN,Jennifer 8. Lee: The hunt for General Tso
444,By analyzing raw data on violent incidents in ...,NaN,Sean Gourley: The mathematics of war
456,"""Bonk"" author Mary Roach delves into obscure s...",NaN,Mary Roach: 10 things you didn't know about or...
478,Organ virtuoso Qi Zhang plays her electric ren...,NaN,Qi Zhang: An electrifying organ performance
539,Advertising adds value to a product by changin...,NaN,Rory Sutherland: Life lessons from an ad man
591,Legendary jazz musician Herbie Hancock deliver...,NaN,Herbie Hancock: An all-star set
670,Some 80 to 90 percent of undersea creatures ma...,NaN,Edith Widder: Glowing life in an underwater world
721,Lego blocks: playtime mainstay for industrious...,NaN,Hillel Cooperman: Legos for grownups

Before we fix the "main_speaker" column, let's shrink our dataset by removing duplicates. 
First we need to see how many duplicates we have:

In [8]:
df['url'].duplicated().sort_values(ascending=False)[:6]

1       True
419     True
426     True
6       True
931     True
0      False
Name: url, dtype: bool

In [9]:
df[(df['url'].duplicated() == False)]

,ID,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
0,0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Emma Rob,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
2,2,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,43,NaN,Al Gore: Averting the climate crisis,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
3,3,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,26,NaN,David Pogue: Simplicity sells,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292
4,4,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,1140912000,35,Majora Carter,Majora Carter: Greening the ghetto,-1,1151367060,"[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550
5,5,593,You've never seen data presented like this. Wi...,1190,TED2006,1140566400,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,1,1151440680,"[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2550,2549,17,"Between 2008 and 2016, the United States depor...",476,TED2017,1496707200,4,Duarte Geraldino,Duarte Geraldino: What we're missing in the de...,1,1505851216,"[{'id': 3, 'name': 'Courageous', 'count': 24},...","[{'id': 2596, 'hero': 'https://pe.tedcdn.com/i...",Journalist,"['TED Residency', 'United States', 'community'...",What we're missing in the debate about immigra...,https://www.ted.com/talks/duarte_geraldino_wha...,450430
2551,2550,6,How can you study Mars without a spaceship? He...,290,TED2017,1492992000,3,Armando Azua-Bustos,Armando Azua-Bustos: The most Martian place on...,1,1505919737,"[{'id': 22, 'name': 'Fascinating', 'count': 32...","[{'id': 2491, 'hero': 'https://pe.tedcdn.com/i...",Astrobiologist,"['Mars', 'South America', 'TED Fellows', 'astr...",The most Martian place on Earth,https://www.ted.com/talks/armando_azua_bustos_...,417470
2552,2551,10,Science fiction visions of the future show us ...,651,TED2017,1492992000,1,Radhika Nagpal,Radhika Nagpal: What intelligent machines can ...,1,1506006095,"[{'id': 1, 'name': 'Beautiful', 'count': 14}, ...","[{'id': 2346, 'hero': 'https://pe.tedcdn.com/i...",Robotics engineer,"['AI', 'ants', 'fish', 'future', 'innovation',...",What intelligent machines can learn from a sch...,https://www.ted.com/talks/radhika_nagpal_what_...,375647
2553,2552,32,In an unmissable talk about race and politics ...,1100,TEDxMileHigh,1499472000,1,Theo E.J. Wilson,Theo E.J. Wilson: A black man goes undercover ...,1,1506024042,"[{'id': 11, 'name': 'Longwinded', 'count': 3},...","[{'id': 2512, 'hero': 'https://pe.tedcdn.com/i...",Public intellectual,"['Internet', 'TEDx', 'United States', 'communi...",A black man goes undercover in the alt-right,https://www.ted.com/talks/theo_e_j_wilson_a_bl...,419309
2554,2553,8,With more than half of the world population li...,519,TED2017,1492992000,1,Karoliina Korppoo,Karoliina Korppoo: How a video game might help...,1,1506092422,"[{'id': 21, 'name': 'Unconvincing', 'count': 2...","[{'id': 2682, 'hero': 'https://pe.tedcdn.com/i...",Game designer,"['cities', 'design', 'future', 'infrastructure...",How a video game might help us build better ci...,https://www.ted.com/talks/karoliina_korppoo_ho...,391721

In [10]:
df[df['url'].duplicated()]

,ID,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
1,1,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Emma Rob,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
6,6,593,You've never seen data presented like this. Wi...,1190,TED2006,1140566400,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,1,1151440680,"[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869
419,419,50,"Singer/songwriter Eddi Reader performs ""What Y...",312,TED2003,1044144000,25,Eddi Reader,"Eddi Reader: ""What You've Got""",2,1176586800,"[{'id': 1, 'name': 'Beautiful', 'count': 272},...","[{'id': 110, 'hero': 'https://pe.tedcdn.com/im...",Singer/songwriter,"['composing', 'entertainment', 'guitar', 'musi...","""What You've Got""",https://www.ted.com/talks/eddi_reader_sings_ab...,428351
426,426,420,"Bonnie Bassler discovered that bacteria ""talk""...",1094,TED2009,1233878400,39,Bonnie Bassler,"Bonnie Bassler: How bacteria ""talk""",1,1239152400,"[{'id': 22, 'name': 'Fascinating', 'count': 27...","[{'id': 519, 'hero': 'https://pe.tedcdn.com/im...",Molecular biologist,"['MacArthur grant', 'bacteria', 'biology', 'co...","How bacteria ""talk""",https://www.ted.com/talks/bonnie_bassler_on_ho...,2192828
931,930,149,Phyllis Rodriguez and Aicha el-Wafi have a pow...,594,TEDWomen 2010,1292112000,32,Aicha el-Wafi + Phyllis Rodriguez,Aicha el-Wafi + Phyllis Rodriguez: The mothers...,1,1304362260,"[{'id': 10, 'name': 'Inspiring', 'count': 385}...","[{'id': 968, 'hero': 'https://pe.tedcdn.com/im...",9/11 mothers,"['culture', 'friendship', 'global issues', 'pa...","The mothers who found forgiveness, friendship",https://www.ted.com/talks/9_11_healing_the_mot...,820976

Then we'll drop the duplicates using the `df.drop_duplicates` method. 

Remember, the keyword `inplace` means it will mutate the original `df`.

In [11]:
help(df.drop_duplicates)

Help on method drop_duplicates in module pandas.core.frame:

drop_duplicates(subset: 'Optional[Union[Hashable, Sequence[Hashable]]]' = None, keep: 'Union[str, bool]' = 'first', inplace: 'bool' = False, ignore_index: 'bool' = False) -> 'Optional[DataFrame]' method of pandas.core.frame.DataFrame instance
    Return DataFrame with duplicate rows removed.

    Considering certain columns is optional. Indexes, including time indexes
    are ignored.

    Parameters
    ----------
    subset : column label or sequence of labels, optional
        Only consider certain columns for identifying duplicates, by
        default use all of the columns.
    keep : {'first', 'last', False}, default 'first'
        Determines which duplicates (if any) to keep.
        - ``first`` : Drop duplicates except for the first occurrence.
        - ``last`` : Drop duplicates except for the last occurrence.
        - False : Drop all duplicates.
    inplace : bool, default False
        Whether to drop duplicates in place or to return a copy.
    ignore_index : bool, default False
        If True, the resulting axis will be labeled 0, 1, …, n - 1.

        .. versionadded:: 1.0.0

    Returns
    -------
    DataFrame or None
        DataFrame with duplicates removed or None if ``inplace=True``.

    See Also
    --------
    DataFrame.value_counts: Count unique combinations of columns.

    Examples
    --------
    Consider dataset containing ramen rating.

    >>> df = pd.DataFrame({
    ...     'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
    ...     'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
    ...     'rating': [4, 4, 3.5, 15, 5]
    ... })
    >>> df
        brand style  rating
    0  Yum Yum   cup     4.0
    1  Yum Yum   cup     4.0
    2  Indomie   cup     3.5
    3  Indomie  pack    15.0
    4  Indomie  pack     5.0

    By default, it removes duplicate rows based on all columns.

    >>> df.drop_duplicates()
        brand style  rating
    0  Yum Yum   cup     4.0
    2  Indomie   cup     3.5
    3  Indomie  pack    15.0
    4  Indomie  pack     5.0

    To remove duplicates on specific column(s), use ``subset``.

    >>> df.drop_duplicates(subset=['brand'])
        brand style  rating
    0  Yum Yum   cup     4.0
    2  Indomie   cup     3.5

    To remove duplicates and keep last occurrences, use ``keep``.

    >>> df.drop_duplicates(subset=['brand', 'style'], keep='last')
        brand style  rating
    1  Yum Yum   cup     4.0
    2  Indomie   cup     3.5
    4  Indomie  pack     5.0

In [12]:
df.drop_duplicates('url', inplace=True)

Next we'll drop the `ID` column as it's unnecessary

In [13]:
df.drop('ID', axis=1, inplace=True)

If we look at `published_date` and `film_date`, they're formatted as unix timestamps. We might need a human-readable format.

[more on unix timestamps](https://en.wikipedia.org/wiki/Unix_time)

In [14]:
df[["published_date", "film_date"]]

      published_date   film_date
0         1151367060  1140825600
2         1151367060  1140825600
3         1151367060  1140739200
4         1151367060  1140912000
5         1151440680  1140566400
...              ...         ...
2550      1505851216  1496707200
2551      1505919737  1492992000
2552      1506006095  1492992000
2553      1506024042  1499472000
2554      1506092422  1492992000

[2550 rows x 2 columns]

Let's see how we can turn a unix timestamp into a human-readable format

In [15]:
ts = 1151367060

s = datetime.datetime.fromtimestamp(ts)

s.strftime("%m/%d/%Y, %H:%M:%S")

'06/26/2006, 20:11:00'

Putting that together, we can create a function that does this for any timestamp

In [16]:
def transform_date(timestamp):
    _date = datetime.datetime.fromtimestamp(timestamp)
    return _date.strftime("%m/%d/%Y, %H:%M:%S")

And then we can test it with a random timestamp

In [17]:
transform_date(1151367060)

'06/26/2006, 20:11:00'

We can use the `df.apply` method to apply that function to each row of a specific column.

In [18]:
df['film_date'].apply(transform_date)

0       02/24/2006, 19:00:00
2       02/24/2006, 19:00:00
3       02/23/2006, 19:00:00
4       02/25/2006, 19:00:00
5       02/21/2006, 19:00:00
                ...
2550    06/05/2017, 20:00:00
2551    04/23/2017, 20:00:00
2552    04/23/2017, 20:00:00
2553    07/07/2017, 20:00:00
2554    04/23/2017, 20:00:00
Name: film_date, Length: 2550, dtype: object

Seeing that it works, we can now use that `transform_date` method along with `apply` to create two new columns of human-readable timestamps

In [19]:
df['film_date_hr'] = df['film_date'].apply(transform_date)
df['published_date_hr'] = df['published_date'].apply(transform_date)

If we wanted to change the ordering of the columns, we can use `df.columns.tolist()` to list our columns and then `df.reindex()` to reindex the columns by passing in a list of columns in the order we want

In [20]:
df.columns.tolist()

['comments',
 'description',
 'duration',
 'event',
 'film_date',
 'languages',
 'main_speaker',
 'name',
 'num_speaker',
 'published_date',
 'ratings',
 'related_talks',
 'speaker_occupation',
 'tags',
 'title',
 'url',
 'views',
 'film_date_hr',
 'published_date_hr']

In [21]:
df = df.reindex(['comments',
 'description',
 'duration',
 'event',
 'film_date',
 'film_date_hr',
 'languages',
 'main_speaker',
 'name',
 'num_speaker',
 'published_date',
 'published_date_hr',
 'ratings',
 'related_talks',
 'speaker_occupation',
 'tags',
 'title',
 'url',
 'views',
],axis=1)

We can see that works by checking the head of the `df`

In [22]:
df.head()

,comments,description,duration,event,film_date,film_date_hr,languages,main_speaker,name,num_speaker,published_date,published_date_hr,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,"02/24/2006, 19:00:00",60,Emma Rob,Ken Robinson: Do schools kill creativity?,1,1151367060,"06/26/2006, 20:11:00","[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
2,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,"02/24/2006, 19:00:00",43,NaN,Al Gore: Averting the climate crisis,1,1151367060,"06/26/2006, 20:11:00","[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
3,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,"02/23/2006, 19:00:00",26,NaN,David Pogue: Simplicity sells,1,1151367060,"06/26/2006, 20:11:00","[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292
4,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,1140912000,"02/25/2006, 19:00:00",35,Majora Carter,Majora Carter: Greening the ghetto,-1,1151367060,"06/26/2006, 20:11:00","[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550
5,593,You've never seen data presented like this. Wi...,1190,TED2006,1140566400,"02/21/2006, 19:00:00",48,Hans Rosling,Hans Rosling: The best stats you've ever seen,1,1151440680,"06/27/2006, 16:38:00","[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869

Next, we'll fix the durations, which are in seconds, by converting them to mins and rounding the result to 2 places after the decimal

In [23]:
df['duration'] = round( df['duration'] / 60, 2)

We'll fix incorrect values for `languages` and `num_speakers` by replacing erroneous values with `1` since we know there's at least one language translated (english) and there's at least one speaker.

In [24]:
df[df['languages'] == 0]

,comments,description,duration,event,film_date,film_date_hr,languages,main_speaker,name,num_speaker,published_date,published_date_hr,ratings,related_talks,speaker_occupation,tags,title,url,views
7,672,"Tony Robbins discusses the ""invisible forces"" ...",21.75,TED2006,1138838400,"02/01/2006, 19:00:00",0,Tony Robbins,Tony Robbins: Why we do what we do,0,1151440680,"06/27/2006, 16:38:00","[{'id': 7, 'name': 'Funny', 'count': 1102}, {'...","[{'id': 229, 'hero': 'https://pe.tedcdn.com/im...",Life coach; expert in leadership psychology,"['business', 'culture', 'entertainment', 'goal...",Why we do what we do,https://www.ted.com/talks/tony_robbins_asks_wh...,20685401
42,58,"Accepting his 2005 TED Prize, photographer Edw...",34.42,TED2005,1108598400,"02/16/2005, 19:00:00",0,Edward Burtynsky,Edward Burtynsky: My wish: Manufactured landsc...,1,1162253460,"10/30/2006, 19:11:00","[{'id': 1, 'name': 'Beautiful', 'count': 106},...","[{'id': 279, 'hero': 'https://pe.tedcdn.com/im...",Photographer,"['TED Prize', 'art', 'cities', 'culture', 'des...",My wish: Manufactured landscapes and green edu...,https://www.ted.com/talks/edward_burtynsky_on_...,975107
49,52,Musician and activist Peter Gabriel shares his...,14.13,TED2006,1140652800,"02/22/2006, 19:00:00",0,Peter Gabriel,Peter Gabriel: Fight injustice with raw video,1,1165363860,"12/05/2006, 19:11:00","[{'id': 3, 'name': 'Courageous', 'count': 180}...","[{'id': 75, 'hero': 'https://pe.tedcdn.com/ima...","Musician, activist","['TED Brain Trust', 'activism', 'art', 'collab...",Fight injustice with raw video,https://www.ted.com/talks/peter_gabriel_fights...,904215
61,222,"Two Pilobolus dancers perform ""Symbiosis."" Doe...",13.75,TED2005,1109289600,"02/24/2005, 19:00:00",0,Pilobolus,"Pilobolus: A dance of ""Symbiosis""",1,1170979860,"02/08/2007, 19:11:00","[{'id': 1, 'name': 'Beautiful', 'count': 1810}...","[{'id': 40, 'hero': 'https://pe.tedcdn.com/ima...",Dance company,"['dance', 'entertainment', 'nature', 'performa...","A dance of ""Symbiosis""",https://www.ted.com/talks/pilobolus_perform_sy...,3051507
89,39,"A happy song about global warming, from Jill S...",2.72,TED2006,1140912000,"02/25/2006, 19:00:00",0,Jill Sobule,"Jill Sobule: Global warming's theme song, ""Man...",1,1175819400,"04/05/2007, 20:30:00","[{'id': 9, 'name': 'Ingenious', 'count': 45}, ...","[{'id': 222, 'hero': 'https://pe.tedcdn.com/im...",Singer/songwriter,"['climate change', 'environment', 'guitar', 'm...","Global warming's theme song, ""Manhattan in Jan...",https://www.ted.com/talks/jill_sobule_sings_to...,591379
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1432,229,"Kid President commands you to wake up, listen ...",3.47,SoulPancake,1358985600,"01/23/2013, 19:00:00",0,Kid President,Kid President: I think we all need a pep talk,1,1359734822,"02/01/2013, 11:07:02","[{'id': 10, 'name': 'Inspiring', 'count': 771}...","[{'id': 815, 'hero': 'https://pe.tedcdn.com/im...",Inspirer,"['children', 'comedy', 'humor']",I think we all need a pep talk,https://www.ted.com/talks/kid_president_i_thin...,828203
1472,183,"As we move through the world, we have an innat...",6.47,TEDYouth 2012,1353110400,"11/16/2012, 19:00:00",0,Katherine Kuchenbecker,Katherine Kuchenbecker: The technology of touch,1,1364569190,"03/29/2013, 10:59:50","[{'id': 9, 'name': 'Ingenious', 'count': 150},...","[{'id': 1692, 'hero': 'https://pe.tedcdn.com/i...",Mechanical engineer,"['TEDYouth', 'engineering', 'technology']",The technology of touch,https://www.ted.com/talks/katherine_kuchenbeck...,274986
1491,126,What color is a mirror? How much does a video ...,7.35,TED-Ed,1362009600,"02/27/2013, 19:00:00",0,Michael Stevens,Michael Stevens: How much does a video weigh?,1,1366815569,"04/24/2013, 10:59:29","[{'id': 22, 'name': 'Fascinating', 'count': 17...","[{'id': 1386, 'hero': 'https://pe.tedcdn.com/i...",YouTube educator,"['Internet', 'TED-Ed', 'computers', 'humor', '...",How much does a video weigh?,https://www.ted.com/talks/how_much_does_a_vide...,195899
2412,5,Grammy-winning Silk Road Ensemble display thei...,6.48,TED2016,1455494400,"02/14/2016, 19:00:00",0,Silk Road Ensemble,"Silk Road Ensemble: ""Turceasca""",1,1489759215,"03/17/2017, 10:00:15","[{'id': 1, 'name': 'Beautiful', 'count': 80}, ...","[{'id': 2611, 'hero': 'https://pe.tedcdn.com/i...",Musical explorers,"['art', 'live music', 'music', 'performance']","""Turceasca""",https://www.ted.com/talks/silk_road_ensemble_t...,640734
2423,11,Sō Percussion creates adventurous compositions...,10.15,TED2016,1455494400,"02/14/2016, 19:00:00",0,Sō Percussion,"Sō Percussion: ""Music for Wood and Strings""",1,1490963646,"03/31/2017, 08:34:06","[{'id': 21, 'name': 'Unconvincing', 'count': 8...","[{'id': 2538, 'hero': 'https://pe.tedcdn.com/i...",Percussion ensemble,"['live music', 'music', 'performance', 'perfor...","""Music for Wood and Strings""",https://www.ted.com/talks/so_percussion_music_...,767660

In [25]:
df['languages'].replace(0, 1, inplace=True)
df

,comments,description,duration,event,film_date,film_date_hr,languages,main_speaker,name,num_speaker,published_date,published_date_hr,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,19.40,TED2006,1140825600,"02/24/2006, 19:00:00",60,Emma Rob,Ken Robinson: Do schools kill creativity?,1,1151367060,"06/26/2006, 20:11:00","[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
2,265,With the same humor and humanity he exuded in ...,16.28,TED2006,1140825600,"02/24/2006, 19:00:00",43,NaN,Al Gore: Averting the climate crisis,1,1151367060,"06/26/2006, 20:11:00","[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
3,124,New York Times columnist David Pogue takes aim...,21.43,TED2006,1140739200,"02/23/2006, 19:00:00",26,NaN,David Pogue: Simplicity sells,1,1151367060,"06/26/2006, 20:11:00","[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292
4,200,"In an emotionally charged talk, MacArthur-winn...",18.60,TED2006,1140912000,"02/25/2006, 19:00:00",35,Majora Carter,Majora Carter: Greening the ghetto,-1,1151367060,"06/26/2006, 20:11:00","[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550
5,593,You've never seen data presented like this. Wi...,19.83,TED2006,1140566400,"02/21/2006, 19:00:00",48,Hans Rosling,Hans Rosling: The best stats you've ever seen,1,1151440680,"06/27/2006, 16:38:00","[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2550,17,"Between 2008 and 2016, the United States depor...",7.93,TED2017,1496707200,"06/05/2017, 20:00:00",4,Duarte Geraldino,Duarte Geraldino: What we're missing in the de...,1,1505851216,"09/19/2017, 16:00:16","[{'id': 3, 'name': 'Courageous', 'count': 24},...","[{'id': 2596, 'hero': 'https://pe.tedcdn.com/i...",Journalist,"['TED Residency', 'United States', 'community'...",What we're missing in the debate about immigra...,https://www.ted.com/talks/duarte_geraldino_wha...,450430
2551,6,How can you study Mars without a spaceship? He...,4.83,TED2017,1492992000,"04/23/2017, 20:00:00",3,Armando Azua-Bustos,Armando Azua-Bustos: The most Martian place on...,1,1505919737,"09/20/2017, 11:02:17","[{'id': 22, 'name': 'Fascinating', 'count': 32...","[{'id': 2491, 'hero': 'https://pe.tedcdn.com/i...",Astrobiologist,"['Mars', 'South America', 'TED Fellows', 'astr...",The most Martian place on Earth,https://www.ted.com/talks/armando_azua_bustos_...,417470
2552,10,Science fiction visions of the future show us ...,10.85,TED2017,1492992000,"04/23/2017, 20:00:00",1,Radhika Nagpal,Radhika Nagpal: What intelligent machines can ...,1,1506006095,"09/21/2017, 11:01:35","[{'id': 1, 'name': 'Beautiful', 'count': 14}, ...","[{'id': 2346, 'hero': 'https://pe.tedcdn.com/i...",Robotics engineer,"['AI', 'ants', 'fish', 'future', 'innovation',...",What intelligent machines can learn from a sch...,https://www.ted.com/talks/radhika_nagpal_what_...,375647
2553,32,In an unmissable talk about race and politics ...,18.33,TEDxMileHigh,1499472000,"07/07/2017, 20:00:00",1,Theo E.J. Wilson,Theo E.J. Wilson: A black man goes undercover ...,1,1506024042,"09/21/2017, 16:00:42","[{'id': 11, 'name': 'Longwinded', 'count': 3},...","[{'id': 2512, 'hero': 'https://pe.tedcdn.com/i...",Public intellectual,"['Internet', 'TEDx', 'United States', 'communi...",A black man goes undercover in the alt-right,https://www.ted.com/talks/theo_e_j_wilson_a_bl...,419309
2554,8,With more than half of the world population li...,8.65,TED2017,1492992000,"04/23/2017, 20:00:00",1,Karoliina Korppoo,Karoliina Korppoo: How a video game might help...,1,1506092422,"09/22/2017, 11:00:22","[{'id': 21, 'name': 'Unconvincing', 'count': 2...","[{'id': 2682, 'hero': 'https://pe.tedcdn.com/i...",Game designer,"['cities', 'design', 'future', 'infrastructure...",How a video game might help us build better ci...,https://www.ted.com/talks/karoliina_korppoo_ho...,391721

In [26]:
df[df['languages'] == 0]

Empty DataFrame
Columns: [comments, description, duration, event, film_date, film_date_hr, languages, main_speaker, name, num_speaker, published_date, published_date_hr, ratings, related_talks, speaker_occupation, tags, title, url, views]
Index: []

In [27]:
df[(df['num_speaker'] <= 0)]

,comments,description,duration,event,film_date,film_date_hr,languages,main_speaker,name,num_speaker,published_date,published_date_hr,ratings,related_talks,speaker_occupation,tags,title,url,views
4,200,"In an emotionally charged talk, MacArthur-winn...",18.60,TED2006,1140912000,"02/25/2006, 19:00:00",35,Majora Carter,Majora Carter: Greening the ghetto,-1,1151367060,"06/26/2006, 20:11:00","[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550
7,672,"Tony Robbins discusses the ""invisible forces"" ...",21.75,TED2006,1138838400,"02/01/2006, 19:00:00",1,Tony Robbins,Tony Robbins: Why we do what we do,0,1151440680,"06/27/2006, 16:38:00","[{'id': 7, 'name': 'Funny', 'count': 1102}, {'...","[{'id': 229, 'hero': 'https://pe.tedcdn.com/im...",Life coach; expert in leadership psychology,"['business', 'culture', 'entertainment', 'goal...",Why we do what we do,https://www.ted.com/talks/tony_robbins_asks_wh...,20685401
15,242,"Jeff Han shows off a cheap, scalable multi-tou...",8.78,TED2006,1139184000,"02/05/2006, 19:00:00",27,Jeff Han,Jeff Han: The radical promise of the multi-tou...,-1,1154391060,"07/31/2006, 20:11:00","[{'id': 9, 'name': 'Ingenious', 'count': 1014}...","[{'id': 685, 'hero': 'https://pe.tedcdn.com/im...",Human-computer interface designer,"['demo', 'design', 'interface design', 'techno...",The radical promise of the multi-touch interface,https://www.ted.com/talks/jeff_han_demos_his_b...,4531020
19,88,Fumes from indoor cooking fires kill more than...,15.10,TED2006,1140739200,"02/23/2006, 19:00:00",27,Amy Smith,Amy Smith: Simple designs to save a life,0,1155600660,"08/14/2006, 20:11:00","[{'id': 9, 'name': 'Ingenious', 'count': 321},...","[{'id': 1561, 'hero': 'https://pe.tedcdn.com/i...","inventor, engineer","['MacArthur grant', 'alternative energy', 'des...",Simple designs to save a life,https://www.ted.com/talks/amy_smith_shares_sim...,1415724
53,85,"Robert Neuwirth, author of ""Shadow Cities,"" fi...",14.05,TEDGlobal 2005,1121299200,"07/13/2005, 20:00:00",22,Robert Neuwirth,Robert Neuwirth: The hidden world of shadow ci...,0,1167696660,"01/01/2007, 19:11:00","[{'id': 8, 'name': 'Informative', 'count': 265...","[{'id': 643, 'hero': 'https://pe.tedcdn.com/im...",Author,"['business', 'cities', 'culture', 'entrepreneu...",The hidden world of shadow cities,https://www.ted.com/talks/robert_neuwirth_on_o...,673036
156,145,Nokia researcher Jan Chipchase's investigation...,16.05,TED2007,1172880000,"03/02/2007, 19:00:00",22,Jan Chipchase,Jan Chipchase: The anthropology of mobile phones,-1,1192716300,"10/18/2007, 10:05:00","[{'id': 8, 'name': 'Informative', 'count': 454...","[{'id': 19, 'hero': 'https://pe.tedcdn.com/ima...",User anthropologist,"['cities', 'communication', 'culture', 'design...",The anthropology of mobile phones,https://www.ted.com/talks/jan_chipchase_on_our...,694378
210,156,Neuroscientist and inventor Christopher deChar...,4.03,TED2008,1204243200,"02/28/2008, 19:00:00",38,Christopher deCharms,Christopher deCharms: A look inside the brain ...,0,1206377160,"03/24/2008, 12:46:00","[{'id': 21, 'name': 'Unconvincing', 'count': 8...","[{'id': 184, 'hero': 'https://pe.tedcdn.com/im...",Brain researcher,"['biology', 'brain', 'business', 'demo', 'medi...",A look inside the brain in real time,https://www.ted.com/talks/christopher_decharms...,1485761
260,59,"The wonderful Nellie McKay sings ""Mother of Pe...",5.57,TED2008,1201910400,"02/01/2008, 19:00:00",24,Nellie McKay,"Nellie McKay: ""Mother of Pearl,"" ""If I Had You""",0,1215756000,"07/11/2008, 02:00:00","[{'id': 10, 'name': 'Inspiring', 'count': 79},...","[{'id': 287, 'hero': 'https://pe.tedcdn.com/im...",Singer/songwriter,"['entertainment', 'humor', 'live music', 'love...","""Mother of Pearl,"" ""If I Had You""",https://www.ted.com/talks/nellie_mckay_sings_f...,1013879
283,174,"Speaking at LIFT 2007, Sugata Mitra talks abou...",20.98,LIFT 2007,1170374400,"02/01/2007, 19:00:00",30,Sugata Mitra,Sugata Mitra: Kids can teach themselves,-1,1219798800,"08/26/2008, 21:00:00","[{'id': 10, 'name': 'Inspiring', 'count': 620}...","[{'id': 66, 'hero': 'https://pe.tedcdn.com/ima...",Education researcher,"['children', 'cities', 'culture', 'education',...",Kids can teach themselves,https://www.ted.com/talks/sugata_mitra_shows_h...,1486853
284,92,Ory Okolloh tells the story of her life and he...,16.63,TEDGlobal 2007,1181088000,"06/05/2007, 20:00:00",19,Ory Okolloh,Ory Okolloh: How I became an activist,-1,1219885200,"08/27/2008, 21:00:00","[{'id': 24, 'name': 'Persuasive', 'count': 68}...","[{'id': 127, 'hero': 'https://pe.tedcdn.com/im...",Blogger and activist,"['Africa', 'activism', 'global issues', 'ident...",How I became an activist,https://www.ted.com/talks/ory_okolloh_on_becom...,321896

In [28]:
df["num_speaker"].replace(0, 1, inplace=True)
df["num_speaker"].replace(-1, 1, inplace=True)

Finally, we're able to get back to the first issue of `main_speaker` having blanks. We can use `df['main_speaker'].isna()` to check the rows of `main_speaker` that are empty

In [29]:
df['main_speaker'].isna()

0       False
2        True
3        True
4       False
5       False
        ...
2550    False
2551    False
2552    False
2553    False
2554    False
Name: main_speaker, Length: 2550, dtype: bool

If we look at the `description`, `main_speaker` and `name` columns for all of the blank rows, we see some useful information

In [30]:
df[df['main_speaker'].isna()][["description", "main_speaker","name"]]

,description,main_speaker,name
2,With the same humor and humanity he exuded in ...,NaN,Al Gore: Averting the climate crisis
3,New York Times columnist David Pogue takes aim...,NaN,David Pogue: Simplicity sells
13,Jehane Noujaim unveils her 2006 TED Prize wish...,NaN,Jehane Noujaim: My wish: A global day of film
34,Cambridge researcher Aubrey de Grey argues tha...,NaN,Aubrey de Grey: A roadmap to end aging
62,Writer and actor Anna Deavere Smith gives life...,NaN,Anna Deavere Smith: Four American characters
75,Graphic designer Stefan Sagmeister takes the a...,NaN,Stefan Sagmeister: Happiness by design
93,Green-minded architect and designer William Mc...,NaN,William McDonough: Cradle to cradle design
123,Alan Russell studies regenerative medicine -- ...,NaN,Alan Russell: The potential of regenerative me...
161,"Lawrence Lessig, the Net’s most celebrated law...",NaN,Lawrence Lessig: Laws that choke creativity
191,What if human consciousness isn't the end-all ...,NaN,Michael Pollan: A plant's-eye view
222,Novelist Amy Tan digs deep into the creative p...,NaN,Amy Tan: Where does creativity hide?
237,"Around the world right now, one billion people...",NaN,"Paul Collier: The ""bottom billion"""
249,Benjamin Zander has two infectious passions: c...,NaN,Benjamin Zander: The transformative power of c...
268,Chris Abani tells stories of people: People st...,NaN,Chris Abani: On humanity
282,"Imagine hearing great, departed pianists play ...",NaN,"John Q. Walker: Great piano performances, recr..."
318,Humorist John Hodgman rambles through a new st...,NaN,"John Hodgman: Aliens, love -- where are they?"
362,Reporter Jennifer 8. Lee talks about her hunt ...,NaN,Jennifer 8. Lee: The hunt for General Tso
444,By analyzing raw data on violent incidents in ...,NaN,Sean Gourley: The mathematics of war
456,"""Bonk"" author Mary Roach delves into obscure s...",NaN,Mary Roach: 10 things you didn't know about or...
478,Organ virtuoso Qi Zhang plays her electric ren...,NaN,Qi Zhang: An electrifying organ performance
539,Advertising adds value to a product by changin...,NaN,Rory Sutherland: Life lessons from an ad man
591,Legendary jazz musician Herbie Hancock deliver...,NaN,Herbie Hancock: An all-star set
670,Some 80 to 90 percent of undersea creatures ma...,NaN,Edith Widder: Glowing life in an underwater world
721,Lego blocks: playtime mainstay for industrious...,NaN,Hillel Cooperman: Legos for grownups

Without that useful information, we can always just replace empty values with a default value like so:

In [31]:
df.fillna("unknown", inplace=True)

In [32]:
df

,comments,description,duration,event,film_date,film_date_hr,languages,main_speaker,name,num_speaker,published_date,published_date_hr,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,19.40,TED2006,1140825600,"02/24/2006, 19:00:00",60,Emma Rob,Ken Robinson: Do schools kill creativity?,1,1151367060,"06/26/2006, 20:11:00","[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
2,265,With the same humor and humanity he exuded in ...,16.28,TED2006,1140825600,"02/24/2006, 19:00:00",43,unknown,Al Gore: Averting the climate crisis,1,1151367060,"06/26/2006, 20:11:00","[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
3,124,New York Times columnist David Pogue takes aim...,21.43,TED2006,1140739200,"02/23/2006, 19:00:00",26,unknown,David Pogue: Simplicity sells,1,1151367060,"06/26/2006, 20:11:00","[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292
4,200,"In an emotionally charged talk, MacArthur-winn...",18.60,TED2006,1140912000,"02/25/2006, 19:00:00",35,Majora Carter,Majora Carter: Greening the ghetto,1,1151367060,"06/26/2006, 20:11:00","[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550
5,593,You've never seen data presented like this. Wi...,19.83,TED2006,1140566400,"02/21/2006, 19:00:00",48,Hans Rosling,Hans Rosling: The best stats you've ever seen,1,1151440680,"06/27/2006, 16:38:00","[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2550,17,"Between 2008 and 2016, the United States depor...",7.93,TED2017,1496707200,"06/05/2017, 20:00:00",4,Duarte Geraldino,Duarte Geraldino: What we're missing in the de...,1,1505851216,"09/19/2017, 16:00:16","[{'id': 3, 'name': 'Courageous', 'count': 24},...","[{'id': 2596, 'hero': 'https://pe.tedcdn.com/i...",Journalist,"['TED Residency', 'United States', 'community'...",What we're missing in the debate about immigra...,https://www.ted.com/talks/duarte_geraldino_wha...,450430
2551,6,How can you study Mars without a spaceship? He...,4.83,TED2017,1492992000,"04/23/2017, 20:00:00",3,Armando Azua-Bustos,Armando Azua-Bustos: The most Martian place on...,1,1505919737,"09/20/2017, 11:02:17","[{'id': 22, 'name': 'Fascinating', 'count': 32...","[{'id': 2491, 'hero': 'https://pe.tedcdn.com/i...",Astrobiologist,"['Mars', 'South America', 'TED Fellows', 'astr...",The most Martian place on Earth,https://www.ted.com/talks/armando_azua_bustos_...,417470
2552,10,Science fiction visions of the future show us ...,10.85,TED2017,1492992000,"04/23/2017, 20:00:00",1,Radhika Nagpal,Radhika Nagpal: What intelligent machines can ...,1,1506006095,"09/21/2017, 11:01:35","[{'id': 1, 'name': 'Beautiful', 'count': 14}, ...","[{'id': 2346, 'hero': 'https://pe.tedcdn.com/i...",Robotics engineer,"['AI', 'ants', 'fish', 'future', 'innovation',...",What intelligent machines can learn from a sch...,https://www.ted.com/talks/radhika_nagpal_what_...,375647
2553,32,In an unmissable talk about race and politics ...,18.33,TEDxMileHigh,1499472000,"07/07/2017, 20:00:00",1,Theo E.J. Wilson,Theo E.J. Wilson: A black man goes undercover ...,1,1506024042,"09/21/2017, 16:00:42","[{'id': 11, 'name': 'Longwinded', 'count': 3},...","[{'id': 2512, 'hero': 'https://pe.tedcdn.com/i...",Public intellectual,"['Internet', 'TEDx', 'United States', 'communi...",A black man goes undercover in the alt-right,https://www.ted.com/talks/theo_e_j_wilson_a_bl...,419309
2554,8,With more than half of the world population li...,8.65,TED2017,1492992000,"04/23/2017, 20:00:00",1,Karoliina Korppoo,Karoliina Korppoo: How a video game might help...,1,1506092422,"09/22/2017, 11:00:22","[{'id': 21, 'name': 'Unconvincing', 'count': 2...","[{'id': 2682, 'hero': 'https://pe.tedcdn.com/i...",Game designer,"['cities', 'design', 'future', 'infrastructure...",How a video game might help us build better ci...,https://www.ted.com/talks/karoliina_korppoo_ho...,391721

In [33]:
df[df['main_speaker'] == 'unknown'].shape

(24, 19)

But here, `name` also contains the speaker's name. So we can rip it and then adjust `main_speaker` and `name` accordingly

In [34]:
df['name'].head()

0        Ken Robinson: Do schools kill creativity?
2             Al Gore: Averting the climate crisis
3                    David Pogue: Simplicity sells
4               Majora Carter: Greening the ghetto
5    Hans Rosling: The best stats you've ever seen
Name: name, dtype: object

In [35]:
df['main_speaker'] = df['name'].str.split(':',1).str[0]

In [36]:
df['name'] = df['name'].str.split(':',1).str[1]

In [37]:
df

,comments,description,duration,event,film_date,film_date_hr,languages,main_speaker,name,num_speaker,published_date,published_date_hr,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,19.40,TED2006,1140825600,"02/24/2006, 19:00:00",60,Ken Robinson,Do schools kill creativity?,1,1151367060,"06/26/2006, 20:11:00","[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
2,265,With the same humor and humanity he exuded in ...,16.28,TED2006,1140825600,"02/24/2006, 19:00:00",43,Al Gore,Averting the climate crisis,1,1151367060,"06/26/2006, 20:11:00","[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
3,124,New York Times columnist David Pogue takes aim...,21.43,TED2006,1140739200,"02/23/2006, 19:00:00",26,David Pogue,Simplicity sells,1,1151367060,"06/26/2006, 20:11:00","[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292
4,200,"In an emotionally charged talk, MacArthur-winn...",18.60,TED2006,1140912000,"02/25/2006, 19:00:00",35,Majora Carter,Greening the ghetto,1,1151367060,"06/26/2006, 20:11:00","[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550
5,593,You've never seen data presented like this. Wi...,19.83,TED2006,1140566400,"02/21/2006, 19:00:00",48,Hans Rosling,The best stats you've ever seen,1,1151440680,"06/27/2006, 16:38:00","[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2550,17,"Between 2008 and 2016, the United States depor...",7.93,TED2017,1496707200,"06/05/2017, 20:00:00",4,Duarte Geraldino,What we're missing in the debate about immigr...,1,1505851216,"09/19/2017, 16:00:16","[{'id': 3, 'name': 'Courageous', 'count': 24},...","[{'id': 2596, 'hero': 'https://pe.tedcdn.com/i...",Journalist,"['TED Residency', 'United States', 'community'...",What we're missing in the debate about immigra...,https://www.ted.com/talks/duarte_geraldino_wha...,450430
2551,6,How can you study Mars without a spaceship? He...,4.83,TED2017,1492992000,"04/23/2017, 20:00:00",3,Armando Azua-Bustos,The most Martian place on Earth,1,1505919737,"09/20/2017, 11:02:17","[{'id': 22, 'name': 'Fascinating', 'count': 32...","[{'id': 2491, 'hero': 'https://pe.tedcdn.com/i...",Astrobiologist,"['Mars', 'South America', 'TED Fellows', 'astr...",The most Martian place on Earth,https://www.ted.com/talks/armando_azua_bustos_...,417470
2552,10,Science fiction visions of the future show us ...,10.85,TED2017,1492992000,"04/23/2017, 20:00:00",1,Radhika Nagpal,What intelligent machines can learn from a sc...,1,1506006095,"09/21/2017, 11:01:35","[{'id': 1, 'name': 'Beautiful', 'count': 14}, ...","[{'id': 2346, 'hero': 'https://pe.tedcdn.com/i...",Robotics engineer,"['AI', 'ants', 'fish', 'future', 'innovation',...",What intelligent machines can learn from a sch...,https://www.ted.com/talks/radhika_nagpal_what_...,375647
2553,32,In an unmissable talk about race and politics ...,18.33,TEDxMileHigh,1499472000,"07/07/2017, 20:00:00",1,Theo E.J. Wilson,A black man goes undercover in the alt-right,1,1506024042,"09/21/2017, 16:00:42","[{'id': 11, 'name': 'Longwinded', 'count': 3},...","[{'id': 2512, 'hero': 'https://pe.tedcdn.com/i...",Public intellectual,"['Internet', 'TEDx', 'United States', 'communi...",A black man goes undercover in the alt-right,https://www.ted.com/talks/theo_e_j_wilson_a_bl...,419309
2554,8,With more than half of the world population li...,8.65,TED2017,1492992000,"04/23/2017, 20:00:00",1,Karoliina Korppoo,How a video game might help us build better c...,1,1506092422,"09/22/2017, 11:00:22","[{'id': 21, 'name': 'Unconvincing', 'count': 2...","[{'id': 2682, 'hero': 'https://pe.tedcdn.com/i...",Game designer,"['cities', 'design', 'future', 'infrastructure...",How a video game might help us build better ci...,https://www.ted.com/talks/karoliina_korppoo_ho...,391721

In [38]:
df['name'][0]

' Do schools kill creativity?'

In [39]:
df["title"][0]

'Do schools kill creativity?'

In [40]:
df['name'] = df['name'].str[1:]

In [41]:
df[~(df['name'] == df['title'])]

,comments,description,duration,event,film_date,film_date_hr,languages,main_speaker,name,num_speaker,published_date,published_date_hr,ratings,related_talks,speaker_occupation,tags,title,url,views
1548,130,"Apes, dolphins and elephants are animals with ...",20.02,TED2013,1362009600,"02/27/2013, 19:00:00",20,The interspecies internet? An idea in progress,NaN,4,1373468405,"07/10/2013, 11:00:05","[{'id': 23, 'name': 'Jaw-dropping', 'count': 5...","[{'id': 1758, 'hero': 'https://pe.tedcdn.com/i...",Cognitive psychologist,"['Internet', 'animals', 'technology']",The interspecies internet? An idea in progress,https://www.ted.com/talks/the_interspecies_int...,717979
1554,153,"Once it's created, plastic (almost) never dies...",9.33,TED2013,1362009600,"02/27/2013, 19:00:00",32,Two young scientists break down plastics with ...,NaN,1,1374160566,"07/18/2013, 11:16:06","[{'id': 9, 'name': 'Ingenious', 'count': 174},...","[{'id': 1239, 'hero': 'https://pe.tedcdn.com/i...",Science fair winners,"['bacteria', 'biology', 'ecology', 'environmen...",Two young scientists break down plastics with ...,https://www.ted.com/talks/two_young_scientists...,1212774
1724,208,"We live in a world of unseeable beauty, so sub...",7.40,TED2014,1395187200,"03/18/2014, 20:00:00",38,Louie Schwartzberg,Hidden miracles of the natural world,1,1397055205,"04/09/2014, 10:53:25","[{'id': 1, 'name': 'Beautiful', 'count': 2341}...","[{'id': 1283, 'hero': 'https://pe.tedcdn.com/i...",Filmmaker,"['bacteria', 'film', 'insects', 'nanoscale', '...",Hidden miracles of the natural world,https://www.ted.com/talks/louie_schwartzberg_h...,7015800
1750,44,Do our smells make us sexy? Popular science su...,14.88,TEDxLeuvenSalon,1379376000,"09/16/2013, 20:00:00",26,Tristram Wyatt,The smelly mystery of the human pheromone,1,1400166002,"05/15/2014, 11:00:02","[{'id': 8, 'name': 'Informative', 'count': 496...","[{'id': 393, 'hero': 'https://pe.tedcdn.com/im...",Zoologist,"['TEDx', 'animals', 'biology', 'smell']",The smelly mystery of the human pheromone,https://www.ted.com/talks/tristram_wyatt_the_s...,1189824
1774,397,Here's a talk that could literally change your...,14.68,TEDSalon NY2014,1400112000,"05/14/2014, 20:00:00",33,Ruth Chang,How to make hard choices,1,1403103639,"06/18/2014, 11:00:39","[{'id': 8, 'name': 'Informative', 'count': 172...","[{'id': 93, 'hero': 'https://pe.tedcdn.com/ima...",Philosopher,"['choice', 'decision-making', 'philosophy']",How to make hard choices,https://www.ted.com/talks/ruth_chang_how_to_ma...,4933802
1850,62,Does a set of data make you feel more comforta...,12.38,TED@IBM,1411603200,"09/24/2014, 20:00:00",25,Susan Etlinger,What do we do with all this big data?,1,1413816332,"10/20/2014, 10:45:32","[{'id': 8, 'name': 'Informative', 'count': 290...","[{'id': 1152, 'hero': 'https://pe.tedcdn.com/i...",Data analyst,['data'],What do we do with all this big data?,https://www.ted.com/talks/susan_etlinger_what_...,1209472
2074,217,Geneticist Jennifer Doudna co-invented a groun...,15.88,TEDGlobal>London,1443484800,"09/28/2015, 20:00:00",29,Jennifer Doudna,How CRISPR lets us edit our DNA,1,1445353411,"10/20/2015, 11:03:31","[{'id': 24, 'name': 'Persuasive', 'count': 145...","[{'id': 35, 'hero': 'https://pe.tedcdn.com/ima...",Biologist,"['Bioethics', 'CRISPR', 'DNA', 'biotech', 'eng...",How CRISPR lets us edit our DNA,https://www.ted.com/talks/jennifer_doudna_we_c...,1936760
2471,20,When Michael Bierut was tapped to design a log...,12.43,TEDNYC,1488931200,"03/07/2017, 19:00:00",16,Michael Bierut,How to design a library that makes kids want t...,1,1496418030,"06/02/2017, 11:40:30","[{'id': 7, 'name': 'Funny', 'count': 111}, {'i...","[{'id': 418, 'hero': 'https://pe.tedcdn.com/im...","Designer, critic","['TEDNYC', 'design', 'education', 'library']",How to design a library that makes kids want t...,https://www.ted.com/talks/michael_bierut_how_t...,1323235
2517,14,It's been a weird 100 years for artists and cr...,10.52,TED2017,1492992000,"04/23/2017, 20:00:00",6,Jack Conte,How artists can (finally) get paid in the digi...,1,1502895617,"08/16/2017, 11:00:17","[{'id': 1, 'name': 'Beautiful', 'count': 31}, ...","[{'id': 1653, 'hero': 'https://pe.tedcdn.com/i...","Musician, entrepreneur","['art', 'business', 'creativity', 'entrepreneu...",How artists can (finally) get paid in the digi...,https://www.ted.com/talks/jack_conte_how_artis...,734095

In [42]:
df[df['name'].isna()]['main_speaker']

1548       The interspecies internet? An idea in progress
1554    Two young scientists break down plastics with ...
Name: main_speaker, dtype: object

In [43]:
df.loc[1548]['main_speaker'] = "unknown"
df.loc[1554]['main_speaker'] = "unknown"

<ipython-input-43-42b7b4c38d32>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[1548]['main_speaker'] = "unknown"
<ipython-input-43-42b7b4c38d32>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[1554]['main_speaker'] = "unknown"

In [44]:
df.drop('name', axis=1, inplace=True)

In [45]:
df

,comments,description,duration,event,film_date,film_date_hr,languages,main_speaker,num_speaker,published_date,published_date_hr,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,19.40,TED2006,1140825600,"02/24/2006, 19:00:00",60,Ken Robinson,1,1151367060,"06/26/2006, 20:11:00","[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
2,265,With the same humor and humanity he exuded in ...,16.28,TED2006,1140825600,"02/24/2006, 19:00:00",43,Al Gore,1,1151367060,"06/26/2006, 20:11:00","[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
3,124,New York Times columnist David Pogue takes aim...,21.43,TED2006,1140739200,"02/23/2006, 19:00:00",26,David Pogue,1,1151367060,"06/26/2006, 20:11:00","[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292
4,200,"In an emotionally charged talk, MacArthur-winn...",18.60,TED2006,1140912000,"02/25/2006, 19:00:00",35,Majora Carter,1,1151367060,"06/26/2006, 20:11:00","[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550
5,593,You've never seen data presented like this. Wi...,19.83,TED2006,1140566400,"02/21/2006, 19:00:00",48,Hans Rosling,1,1151440680,"06/27/2006, 16:38:00","[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2550,17,"Between 2008 and 2016, the United States depor...",7.93,TED2017,1496707200,"06/05/2017, 20:00:00",4,Duarte Geraldino,1,1505851216,"09/19/2017, 16:00:16","[{'id': 3, 'name': 'Courageous', 'count': 24},...","[{'id': 2596, 'hero': 'https://pe.tedcdn.com/i...",Journalist,"['TED Residency', 'United States', 'community'...",What we're missing in the debate about immigra...,https://www.ted.com/talks/duarte_geraldino_wha...,450430
2551,6,How can you study Mars without a spaceship? He...,4.83,TED2017,1492992000,"04/23/2017, 20:00:00",3,Armando Azua-Bustos,1,1505919737,"09/20/2017, 11:02:17","[{'id': 22, 'name': 'Fascinating', 'count': 32...","[{'id': 2491, 'hero': 'https://pe.tedcdn.com/i...",Astrobiologist,"['Mars', 'South America', 'TED Fellows', 'astr...",The most Martian place on Earth,https://www.ted.com/talks/armando_azua_bustos_...,417470
2552,10,Science fiction visions of the future show us ...,10.85,TED2017,1492992000,"04/23/2017, 20:00:00",1,Radhika Nagpal,1,1506006095,"09/21/2017, 11:01:35","[{'id': 1, 'name': 'Beautiful', 'count': 14}, ...","[{'id': 2346, 'hero': 'https://pe.tedcdn.com/i...",Robotics engineer,"['AI', 'ants', 'fish', 'future', 'innovation',...",What intelligent machines can learn from a sch...,https://www.ted.com/talks/radhika_nagpal_what_...,375647
2553,32,In an unmissable talk about race and politics ...,18.33,TEDxMileHigh,1499472000,"07/07/2017, 20:00:00",1,Theo E.J. Wilson,1,1506024042,"09/21/2017, 16:00:42","[{'id': 11, 'name': 'Longwinded', 'count': 3},...","[{'id': 2512, 'hero': 'https://pe.tedcdn.com/i...",Public intellectual,"['Internet', 'TEDx', 'United States', 'communi...",A black man goes undercover in the alt-right,https://www.ted.com/talks/theo_e_j_wilson_a_bl...,419309
2554,8,With more than half of the world population li...,8.65,TED2017,1492992000,"04/23/2017, 20:00:00",1,Karoliina Korppoo,1,1506092422,"09/22/2017, 11:00:22","[{'id': 21, 'name': 'Unconvincing', 'count': 2...","[{'id': 2682, 'hero': 'https://pe.tedcdn.com/i...",Game designer,"['cities', 'design', 'future', 'infrastructure...",How a video game might help us build better ci...,https://www.ted.com/talks/karoliina_korppoo_ho...,391721

In [46]:
df.columns.tolist()

['comments',
 'description',
 'duration',
 'event',
 'film_date',
 'film_date_hr',
 'languages',
 'main_speaker',
 'num_speaker',
 'published_date',
 'published_date_hr',
 'ratings',
 'related_talks',
 'speaker_occupation',
 'tags',
 'title',
 'url',
 'views']

In [47]:
df = df.reindex([
'title',
 'description',
 'main_speaker',
 'speaker_occupation',
 'num_speaker',
 'languages',
 'duration',
 'event',
 'tags',
 'ratings',
 'related_talks',
 'film_date',
 'film_date_hr',
 'published_date',
 'published_date_hr',
 'url',
 'comments',
 'views' 
], axis=1)

In [48]:
df

,title,description,main_speaker,speaker_occupation,num_speaker,languages,duration,event,tags,ratings,related_talks,film_date,film_date_hr,published_date,published_date_hr,url,comments,views
0,Do schools kill creativity?,Sir Ken Robinson makes an entertaining and pro...,Ken Robinson,Author/educator,1,60,19.40,TED2006,"['children', 'creativity', 'culture', 'dance',...","[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",1140825600,"02/24/2006, 19:00:00",1151367060,"06/26/2006, 20:11:00",https://www.ted.com/talks/ken_robinson_says_sc...,4553,47227110
2,Averting the climate crisis,With the same humor and humanity he exuded in ...,Al Gore,Climate advocate,1,43,16.28,TED2006,"['alternative energy', 'cars', 'climate change...","[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",1140825600,"02/24/2006, 19:00:00",1151367060,"06/26/2006, 20:11:00",https://www.ted.com/talks/al_gore_on_averting_...,265,3200520
3,Simplicity sells,New York Times columnist David Pogue takes aim...,David Pogue,Technology columnist,1,26,21.43,TED2006,"['computers', 'entertainment', 'interface desi...","[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",1140739200,"02/23/2006, 19:00:00",1151367060,"06/26/2006, 20:11:00",https://www.ted.com/talks/david_pogue_says_sim...,124,1636292
4,Greening the ghetto,"In an emotionally charged talk, MacArthur-winn...",Majora Carter,Activist for environmental justice,1,35,18.60,TED2006,"['MacArthur grant', 'activism', 'business', 'c...","[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",1140912000,"02/25/2006, 19:00:00",1151367060,"06/26/2006, 20:11:00",https://www.ted.com/talks/majora_carter_s_tale...,200,1697550
5,The best stats you've ever seen,You've never seen data presented like this. Wi...,Hans Rosling,Global health expert; data visionary,1,48,19.83,TED2006,"['Africa', 'Asia', 'Google', 'demo', 'economic...","[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",1140566400,"02/21/2006, 19:00:00",1151440680,"06/27/2006, 16:38:00",https://www.ted.com/talks/hans_rosling_shows_t...,593,12005869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2550,What we're missing in the debate about immigra...,"Between 2008 and 2016, the United States depor...",Duarte Geraldino,Journalist,1,4,7.93,TED2017,"['TED Residency', 'United States', 'community'...","[{'id': 3, 'name': 'Courageous', 'count': 24},...","[{'id': 2596, 'hero': 'https://pe.tedcdn.com/i...",1496707200,"06/05/2017, 20:00:00",1505851216,"09/19/2017, 16:00:16",https://www.ted.com/talks/duarte_geraldino_wha...,17,450430
2551,The most Martian place on Earth,How can you study Mars without a spaceship? He...,Armando Azua-Bustos,Astrobiologist,1,3,4.83,TED2017,"['Mars', 'South America', 'TED Fellows', 'astr...","[{'id': 22, 'name': 'Fascinating', 'count': 32...","[{'id': 2491, 'hero': 'https://pe.tedcdn.com/i...",1492992000,"04/23/2017, 20:00:00",1505919737,"09/20/2017, 11:02:17",https://www.ted.com/talks/armando_azua_bustos_...,6,417470
2552,What intelligent machines can learn from a sch...,Science fiction visions of the future show us ...,Radhika Nagpal,Robotics engineer,1,1,10.85,TED2017,"['AI', 'ants', 'fish', 'future', 'innovation',...","[{'id': 1, 'name': 'Beautiful', 'count': 14}, ...","[{'id': 2346, 'hero': 'https://pe.tedcdn.com/i...",1492992000,"04/23/2017, 20:00:00",1506006095,"09/21/2017, 11:01:35",https://www.ted.com/talks/radhika_nagpal_what_...,10,375647
2553,A black man goes undercover in the alt-right,In an unmissable talk about race and politics ...,Theo E.J. Wilson,Public intellectual,1,1,18.33,TEDxMileHigh,"['Internet', 'TEDx', 'United States', 'communi...","[{'id': 11, 'name': 'Longwinded', 'count': 3},...","[{'id': 2512, 'hero': 'https://pe.tedcdn.com/i...",1499472000,"07/07/2017, 20:00:00",1506024042,"09/21/2017, 16:00:42",https://www.ted.com/talks/theo_e_j_wilson_a_bl...,32,419309
2554,How a video game might help us build better ci...,With more than half of the world population li...,Karoliina Korppoo,Game designer,1,1,8.65,TED2017,"['cities', 'design', 'future', 'infrastructure...","[{'id': 21, 'name': 'Unconvincing', 'count': 2...","[{'id': 2682, 'hero': 'https://pe.tedcdn.com/i...",1492992000,"04/23/2017, 20:00:00",1506092422,"09/22/2017, 11:00:22",https://www.ted.com/talks/karoliina_korppoo_ho...,8,391721

In [49]:
s = df['ratings'][0]
s

"[{'id': 7, 'name': 'Funny', 'count': 19645}, {'id': 1, 'name': 'Beautiful', 'count': 4573}, {'id': 9, 'name': 'Ingenious', 'count': 6073}, {'id': 3, 'name': 'Courageous', 'count': 3253}, {'id': 11, 'name': 'Longwinded', 'count': 387}, {'id': 2, 'name': 'Confusing', 'count': 242}, {'id': 8, 'name': 'Informative', 'count': 7346}, {'id': 22, 'name': 'Fascinating', 'count': 10581}, {'id': 21, 'name': 'Unconvincing', 'count': 300}, {'id': 24, 'name': 'Persuasive', 'count': 10704}, {'id': 23, 'name': 'Jaw-dropping', 'count': 4439}, {'id': 25, 'name': 'OK', 'count': 1174}, {'id': 26, 'name': 'Obnoxious', 'count': 209}, {'id': 10, 'name': 'Inspiring', 'count': 24924}]"

In [50]:
f = eval(s)
f

[{'id': 7, 'name': 'Funny', 'count': 19645},
 {'id': 1, 'name': 'Beautiful', 'count': 4573},
 {'id': 9, 'name': 'Ingenious', 'count': 6073},
 {'id': 3, 'name': 'Courageous', 'count': 3253},
 {'id': 11, 'name': 'Longwinded', 'count': 387},
 {'id': 2, 'name': 'Confusing', 'count': 242},
 {'id': 8, 'name': 'Informative', 'count': 7346},
 {'id': 22, 'name': 'Fascinating', 'count': 10581},
 {'id': 21, 'name': 'Unconvincing', 'count': 300},
 {'id': 24, 'name': 'Persuasive', 'count': 10704},
 {'id': 23, 'name': 'Jaw-dropping', 'count': 4439},
 {'id': 25, 'name': 'OK', 'count': 1174},
 {'id': 26, 'name': 'Obnoxious', 'count': 209},
 {'id': 10, 'name': 'Inspiring', 'count': 24924}]

In [51]:
d = {}
for i in f:
    d[i['name']] = {'id': i['id'], 'count': i['count']}

In [52]:
d['Funny']['count']

19645

In [57]:
def convert_ratings(rating):
    d = {}
    for i in eval(rating):
        d[i['name'].lower()] = {'id': i['id'], 'count': i['count']}
    return d

In [58]:
convert_ratings(df['ratings'][30])

{'funny': {'id': 7, 'count': 1668},
 'ingenious': {'id': 9, 'count': 1127},
 'beautiful': {'id': 1, 'count': 333},
 'longwinded': {'id': 11, 'count': 190},
 'confusing': {'id': 2, 'count': 80},
 'courageous': {'id': 3, 'count': 87},
 'unconvincing': {'id': 21, 'count': 115},
 'informative': {'id': 8, 'count': 2004},
 'inspiring': {'id': 10, 'count': 1276},
 'fascinating': {'id': 22, 'count': 2082},
 'persuasive': {'id': 24, 'count': 1014},
 'jaw-dropping': {'id': 23, 'count': 290},
 'ok': {'id': 25, 'count': 361},
 'obnoxious': {'id': 26, 'count': 51}}

In [75]:
df['ratings'].apply(convert_ratings)

0       {'funny': {'id': 7, 'count': 19645}, 'beautifu...
2       {'funny': {'id': 7, 'count': 544}, 'courageous...
3       {'funny': {'id': 7, 'count': 964}, 'courageous...
4       {'courageous': {'id': 3, 'count': 760}, 'beaut...
5       {'ingenious': {'id': 9, 'count': 3202}, 'funny...
                              ...
2550    {'courageous': {'id': 3, 'count': 24}, 'inform...
2551    {'fascinating': {'id': 22, 'count': 32}, 'info...
2552    {'beautiful': {'id': 1, 'count': 14}, 'informa...
2553    {'longwinded': {'id': 11, 'count': 3}, 'unconv...
2554    {'unconvincing': {'id': 21, 'count': 21}, 'inf...
Name: ratings, Length: 2550, dtype: object

In [68]:
df

,title,description,main_speaker,speaker_occupation,num_speaker,languages,duration,event,tags,ratings,related_talks,film_date,film_date_hr,published_date,published_date_hr,url,comments,views
0,Do schools kill creativity?,Sir Ken Robinson makes an entertaining and pro...,Ken Robinson,Author/educator,1,60,19.40,TED2006,"['children', 'creativity', 'culture', 'dance',...","[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",1140825600,"02/24/2006, 19:00:00",1151367060,"06/26/2006, 20:11:00",https://www.ted.com/talks/ken_robinson_says_sc...,4553,47227110
2,Averting the climate crisis,With the same humor and humanity he exuded in ...,Al Gore,Climate advocate,1,43,16.28,TED2006,"['alternative energy', 'cars', 'climate change...","[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",1140825600,"02/24/2006, 19:00:00",1151367060,"06/26/2006, 20:11:00",https://www.ted.com/talks/al_gore_on_averting_...,265,3200520
3,Simplicity sells,New York Times columnist David Pogue takes aim...,David Pogue,Technology columnist,1,26,21.43,TED2006,"['computers', 'entertainment', 'interface desi...","[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",1140739200,"02/23/2006, 19:00:00",1151367060,"06/26/2006, 20:11:00",https://www.ted.com/talks/david_pogue_says_sim...,124,1636292
4,Greening the ghetto,"In an emotionally charged talk, MacArthur-winn...",Majora Carter,Activist for environmental justice,1,35,18.60,TED2006,"['MacArthur grant', 'activism', 'business', 'c...","[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",1140912000,"02/25/2006, 19:00:00",1151367060,"06/26/2006, 20:11:00",https://www.ted.com/talks/majora_carter_s_tale...,200,1697550
5,The best stats you've ever seen,You've never seen data presented like this. Wi...,Hans Rosling,Global health expert; data visionary,1,48,19.83,TED2006,"['Africa', 'Asia', 'Google', 'demo', 'economic...","[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",1140566400,"02/21/2006, 19:00:00",1151440680,"06/27/2006, 16:38:00",https://www.ted.com/talks/hans_rosling_shows_t...,593,12005869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2550,What we're missing in the debate about immigra...,"Between 2008 and 2016, the United States depor...",Duarte Geraldino,Journalist,1,4,7.93,TED2017,"['TED Residency', 'United States', 'community'...","[{'id': 3, 'name': 'Courageous', 'count': 24},...","[{'id': 2596, 'hero': 'https://pe.tedcdn.com/i...",1496707200,"06/05/2017, 20:00:00",1505851216,"09/19/2017, 16:00:16",https://www.ted.com/talks/duarte_geraldino_wha...,17,450430
2551,The most Martian place on Earth,How can you study Mars without a spaceship? He...,Armando Azua-Bustos,Astrobiologist,1,3,4.83,TED2017,"['Mars', 'South America', 'TED Fellows', 'astr...","[{'id': 22, 'name': 'Fascinating', 'count': 32...","[{'id': 2491, 'hero': 'https://pe.tedcdn.com/i...",1492992000,"04/23/2017, 20:00:00",1505919737,"09/20/2017, 11:02:17",https://www.ted.com/talks/armando_azua_bustos_...,6,417470
2552,What intelligent machines can learn from a sch...,Science fiction visions of the future show us ...,Radhika Nagpal,Robotics engineer,1,1,10.85,TED2017,"['AI', 'ants', 'fish', 'future', 'innovation',...","[{'id': 1, 'name': 'Beautiful', 'count': 14}, ...","[{'id': 2346, 'hero': 'https://pe.tedcdn.com/i...",1492992000,"04/23/2017, 20:00:00",1506006095,"09/21/2017, 11:01:35",https://www.ted.com/talks/radhika_nagpal_what_...,10,375647
2553,A black man goes undercover in the alt-right,In an unmissable talk about race and politics ...,Theo E.J. Wilson,Public intellectual,1,1,18.33,TEDxMileHigh,"['Internet', 'TEDx', 'United States', 'communi...","[{'id': 11, 'name': 'Longwinded', 'count': 3},...","[{'id': 2512, 'hero': 'https://pe.tedcdn.com/i...",1499472000,"07/07/2017, 20:00:00",1506024042,"09/21/2017, 16:00:42",https://www.ted.com/talks/theo_e_j_wilson_a_bl...,32,419309
2554,How a video game might help us build better ci...,With more than half of the world population li...,Karoliina Korppoo,Game designer,1,1,8.65,TED2017,"['cities', 'design', 'future', 'infrastructure...","[{'id': 21, 'name': 'Unconvincing', 'count': 2...","[{'id': 2682, 'hero': 'https://pe.tedcdn.com/i...",1492992000,"04/23/2017, 20:00:00",1506092422,"09/22/2017, 11:00:22",https://www.ted.com/talks/karoliina_korppoo_ho...,8,391721

In [67]:
eval(df['related_talks'][0])

[{'id': 865,
  'hero': 'https://pe.tedcdn.com/images/ted/172559_800x600.jpg',
  'speaker': 'Ken Robinson',
  'title': 'Bring on the learning revolution!',
  'duration': 1008,
  'slug': 'sir_ken_robinson_bring_on_the_revolution',
  'viewed_count': 7266103},
 {'id': 1738,
  'hero': 'https://pe.tedcdn.com/images/ted/de98b161ad1434910ff4b56c89de71af04b8b873_1600x1200.jpg',
  'speaker': 'Ken Robinson',
  'title': "How to escape education's death valley",
  'duration': 1151,
  'slug': 'ken_robinson_how_to_escape_education_s_death_valley',
  'viewed_count': 6657572},
 {'id': 2276,
  'hero': 'https://pe.tedcdn.com/images/ted/3821f3728e0b755c7b9aea2e69cc093eca41abe1_2880x1620.jpg',
  'speaker': 'Linda Cliatt-Wayman',
  'title': 'How to fix a broken school? Lead fearlessly, love hard',
  'duration': 1027,
  'slug': 'linda_cliatt_wayman_how_to_fix_a_broken_school_lead_fearlessly_love_hard',
  'viewed_count': 1617101},
 {'id': 892,
  'hero': 'https://pe.tedcdn.com/images/ted/e79958940573cc610ccb583619a54866c41ef303_2880x1620.jpg',
  'speaker': 'Charles Leadbeater',
  'title': 'Education innovation in the slums',
  'duration': 1138,
  'slug': 'charles_leadbeater_on_education',
  'viewed_count': 772296},
 {'id': 1232,
  'hero': 'https://pe.tedcdn.com/images/ted/0e3e4e92d5ee8ae0e43962d447d3f790b31099b8_800x600.jpg',
  'speaker': 'Geoff Mulgan',
  'title': 'A short intro to the Studio School',
  'duration': 376,
  'slug': 'geoff_mulgan_a_short_intro_to_the_studio_school',
  'viewed_count': 667971},
 {'id': 2616,
  'hero': 'https://pe.tedcdn.com/images/ted/71cde5a6fa6c717488fb55eff9eef939a9241761_2880x1620.jpg',
  'speaker': 'Kandice Sumner',
  'title': "How America's public schools keep kids in poverty",
  'duration': 830,
  'slug': 'kandice_sumner_how_america_s_public_schools_keep_kids_in_poverty',
  'viewed_count': 1181333}]

In [69]:
df[df['title'] == "Bring on the learning revolution!"]

,title,description,main_speaker,speaker_occupation,num_speaker,languages,duration,event,tags,ratings,related_talks,film_date,film_date_hr,published_date,published_date_hr,url,comments,views
696,Bring on the learning revolution!,"In this poignant, funny follow-up to his fable...",Ken Robinson,Author/educator,1,57,16.8,TED2010,"['TED Brain Trust', 'children', 'creativity', ...","[{'id': 7, 'name': 'Funny', 'count': 3000}, {'...","[{'id': 66, 'hero': 'https://pe.tedcdn.com/ima...",1265414400,"02/05/2010, 19:00:00",1274691960,"05/24/2010, 05:06:00",https://www.ted.com/talks/sir_ken_robinson_bri...,1234,7266316

In [70]:
def convert_related(related):
    return [i['title'] for i in eval(related)]

In [71]:
convert_related(df['related_talks'][23])

['The  4 a.m. mystery',
 'My web playroom',
 'Are you human?',
 'How to find a wonderful idea',
 'Visualizing ourselves ... with crowd-sourced data',
 'How artists can (finally) get paid in the digital age ']

In [72]:
df[df['title'] == 'Are you human?']

,title,description,main_speaker,speaker_occupation,num_speaker,languages,duration,event,tags,ratings,related_talks,film_date,film_date_hr,published_date,published_date_hr,url,comments,views
1796,Are you human?,Have you ever wondered: Am I a human being? Ze...,Ze Frank,"Humorist, web artist",1,44,4.57,TED2014,"['comedy', 'community', 'entertainment', 'huma...","[{'id': 7, 'name': 'Funny', 'count': 1812}, {'...","[{'id': 981, 'hero': 'https://pe.tedcdn.com/im...",1395273600,"03/19/2014, 20:00:00",1405696133,"07/18/2014, 11:08:53",https://www.ted.com/talks/ze_frank_are_you_hum...,251,4058219

In [73]:
df['related_talks'] = df['related_talks'].apply(convert_related)

In [76]:
df['ratings'] = df['ratings'].apply(convert_ratings)

In [79]:
df['ratings'][34].keys()

dict_keys(['unconvincing', 'funny', 'courageous', 'longwinded', 'confusing', 'ingenious', 'beautiful', 'informative', 'inspiring', 'fascinating', 'persuasive', 'ok', 'jaw-dropping', 'obnoxious'])

In [80]:
df

,title,description,main_speaker,speaker_occupation,num_speaker,languages,duration,event,tags,ratings,related_talks,film_date,film_date_hr,published_date,published_date_hr,url,comments,views
0,Do schools kill creativity?,Sir Ken Robinson makes an entertaining and pro...,Ken Robinson,Author/educator,1,60,19.40,TED2006,"['children', 'creativity', 'culture', 'dance',...","{'funny': {'id': 7, 'count': 19645}, 'beautifu...","[Bring on the learning revolution!, How to esc...",1140825600,"02/24/2006, 19:00:00",1151367060,"06/26/2006, 20:11:00",https://www.ted.com/talks/ken_robinson_says_sc...,4553,47227110
2,Averting the climate crisis,With the same humor and humanity he exuded in ...,Al Gore,Climate advocate,1,43,16.28,TED2006,"['alternative energy', 'cars', 'climate change...","{'funny': {'id': 7, 'count': 544}, 'courageous...","[New thinking on the climate crisis, The busin...",1140825600,"02/24/2006, 19:00:00",1151367060,"06/26/2006, 20:11:00",https://www.ted.com/talks/al_gore_on_averting_...,265,3200520
3,Simplicity sells,New York Times columnist David Pogue takes aim...,David Pogue,Technology columnist,1,26,21.43,TED2006,"['computers', 'entertainment', 'interface desi...","{'funny': {'id': 7, 'count': 964}, 'courageous...","[10 top time-saving tech tips, The first secre...",1140739200,"02/23/2006, 19:00:00",1151367060,"06/26/2006, 20:11:00",https://www.ted.com/talks/david_pogue_says_sim...,124,1636292
4,Greening the ghetto,"In an emotionally charged talk, MacArthur-winn...",Majora Carter,Activist for environmental justice,1,35,18.60,TED2006,"['MacArthur grant', 'activism', 'business', 'c...","{'courageous': {'id': 3, 'count': 760}, 'beaut...","[3 stories of local eco-entrepreneurship, A ne...",1140912000,"02/25/2006, 19:00:00",1151367060,"06/26/2006, 20:11:00",https://www.ted.com/talks/majora_carter_s_tale...,200,1697550
5,The best stats you've ever seen,You've never seen data presented like this. Wi...,Hans Rosling,Global health expert; data visionary,1,48,19.83,TED2006,"['Africa', 'Asia', 'Google', 'demo', 'economic...","{'ingenious': {'id': 9, 'count': 3202}, 'funny...","[Own your body's data, A visual history of hum...",1140566400,"02/21/2006, 19:00:00",1151440680,"06/27/2006, 16:38:00",https://www.ted.com/talks/hans_rosling_shows_t...,593,12005869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2550,What we're missing in the debate about immigra...,"Between 2008 and 2016, the United States depor...",Duarte Geraldino,Journalist,1,4,7.93,TED2017,"['TED Residency', 'United States', 'community'...","{'courageous': {'id': 3, 'count': 24}, 'inform...","[Immigrant voices make democracy stronger, Why...",1496707200,"06/05/2017, 20:00:00",1505851216,"09/19/2017, 16:00:16",https://www.ted.com/talks/duarte_geraldino_wha...,17,450430
2551,The most Martian place on Earth,How can you study Mars without a spaceship? He...,Armando Azua-Bustos,Astrobiologist,1,3,4.83,TED2017,"['Mars', 'South America', 'TED Fellows', 'astr...","{'fascinating': {'id': 22, 'count': 32}, 'info...","[Adventures of an asteroid hunter, Why Earth m...",1492992000,"04/23/2017, 20:00:00",1505919737,"09/20/2017, 11:02:17",https://www.ted.com/talks/armando_azua_bustos_...,6,417470
2552,What intelligent machines can learn from a sch...,Science fiction visions of the future show us ...,Radhika Nagpal,Robotics engineer,1,1,10.85,TED2017,"['AI', 'ants', 'fish', 'future', 'innovation',...","{'beautiful': {'id': 1, 'count': 14}, 'informa...","[The future of flying robots, Meet Spot, the r...",1492992000,"04/23/2017, 20:00:00",1506006095,"09/21/2017, 11:01:35",https://www.ted.com/talks/radhika_nagpal_what_...,10,375647
2553,A black man goes undercover in the alt-right,In an unmissable talk about race and politics ...,Theo E.J. Wilson,Public intellectual,1,1,18.33,TEDxMileHigh,"['Internet', 'TEDx', 'United States', 'communi...","{'longwinded': {'id': 11, 'count': 3}, 'unconv...","[How barbershops can keep men healthy, We need...",1499472000,"07/07/2017, 20:00:00",1506024042,"09/21/2017, 16:00:42",https://www.ted.com/talks/theo_e_j_wilson_a_bl...,32,419309
2554,How a video game might help us build better ci...,With more than half of the world population li...,Karoliina Korppoo,Game designer,1,1,8.65,TED2017,"['cities', 'design', 'future', 'infrastructure...","{'unconvincing': {'id': 21, 'count': 21}, 'inf...","[4 ways to make a city more walkable, 7 princi...",1492992000,"04/23/2017, 20:00:00",1506092422,"09/22/2017, 11:00:22",https://www.ted.com/talks/karoliina_korppoo_ho...,8,391721

In [81]:
df2 = pd.read_csv('../datasets/ted_talks_transcripts.csv')

In [90]:
df2.iloc[:,:2]

,transcript,url
0,Good morning. How are you?(Laughter)It's been ...,https://www.ted.com/talks/ken_robinson_says_sc...
1,"Thank you so much, Chris. And it's truly a gre...",https://www.ted.com/talks/al_gore_on_averting_...
2,"(Music: ""The Sound of Silence,"" Simon & Garfun...",https://www.ted.com/talks/david_pogue_says_sim...
3,If you're here today — and I'm very happy that...,https://www.ted.com/talks/majora_carter_s_tale...
4,"About 10 years ago, I took on the task to teac...",https://www.ted.com/talks/hans_rosling_shows_t...
...,...,...
2470,"So, Ma was trying to explain something to me a...",https://www.ted.com/talks/duarte_geraldino_wha...
2471,This is a picture of a sunset on Mars taken by...,https://www.ted.com/talks/armando_azua_bustos_...
2472,"In my early days as a graduate student, I went...",https://www.ted.com/talks/radhika_nagpal_what_...
2473,I took a cell phone and accidentally made myse...,https://www.ted.com/talks/theo_e_j_wilson_a_bl...
2474,"We humans are becoming an urban species, so ci...",https://www.ted.com/talks/karoliina_korppoo_ho...

In [ ]:
help(df.merge)

In [95]:
df = df.merge(df2.iloc[:,:2], on="url")

In [96]:
df.to_csv('../datasets/cleaned_ted_talks.csv', index=False)

In [97]:
cleaned_df = pd.read_csv('../datasets/cleaned_ted_talks.csv')

In [100]:
cleaned_df

,title,description,main_speaker,speaker_occupation,num_speaker,languages,duration,event,tags,ratings,related_talks,film_date,film_date_hr,published_date,published_date_hr,url,comments,views,transcript
0,Do schools kill creativity?,Sir Ken Robinson makes an entertaining and pro...,Ken Robinson,Author/educator,1,60,19.40,TED2006,"['children', 'creativity', 'culture', 'dance',...","{'funny': {'id': 7, 'count': 19645}, 'beautifu...","['Bring on the learning revolution!', ""How to ...",1140825600,"02/24/2006, 19:00:00",1151367060,"06/26/2006, 20:11:00",https://www.ted.com/talks/ken_robinson_says_sc...,4553,47227110,Good morning. How are you?(Laughter)It's been ...
1,Averting the climate crisis,With the same humor and humanity he exuded in ...,Al Gore,Climate advocate,1,43,16.28,TED2006,"['alternative energy', 'cars', 'climate change...","{'funny': {'id': 7, 'count': 544}, 'courageous...","['New thinking on the climate crisis', 'The bu...",1140825600,"02/24/2006, 19:00:00",1151367060,"06/26/2006, 20:11:00",https://www.ted.com/talks/al_gore_on_averting_...,265,3200520,"Thank you so much, Chris. And it's truly a gre..."
2,Simplicity sells,New York Times columnist David Pogue takes aim...,David Pogue,Technology columnist,1,26,21.43,TED2006,"['computers', 'entertainment', 'interface desi...","{'funny': {'id': 7, 'count': 964}, 'courageous...","['10 top time-saving tech tips', 'The first se...",1140739200,"02/23/2006, 19:00:00",1151367060,"06/26/2006, 20:11:00",https://www.ted.com/talks/david_pogue_says_sim...,124,1636292,"(Music: ""The Sound of Silence,"" Simon & Garfun..."
3,Greening the ghetto,"In an emotionally charged talk, MacArthur-winn...",Majora Carter,Activist for environmental justice,1,35,18.60,TED2006,"['MacArthur grant', 'activism', 'business', 'c...","{'courageous': {'id': 3, 'count': 760}, 'beaut...","['3 stories of local eco-entrepreneurship', 'A...",1140912000,"02/25/2006, 19:00:00",1151367060,"06/26/2006, 20:11:00",https://www.ted.com/talks/majora_carter_s_tale...,200,1697550,If you're here today — and I'm very happy that...
4,The best stats you've ever seen,You've never seen data presented like this. Wi...,Hans Rosling,Global health expert; data visionary,1,48,19.83,TED2006,"['Africa', 'Asia', 'Google', 'demo', 'economic...","{'ingenious': {'id': 9, 'count': 3202}, 'funny...","[""Own your body's data"", 'A visual history of ...",1140566400,"02/21/2006, 19:00:00",1151440680,"06/27/2006, 16:38:00",https://www.ted.com/talks/hans_rosling_shows_t...,593,12005869,"About 10 years ago, I took on the task to teac..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2458,What we're missing in the debate about immigra...,"Between 2008 and 2016, the United States depor...",Duarte Geraldino,Journalist,1,4,7.93,TED2017,"['TED Residency', 'United States', 'community'...","{'courageous': {'id': 3, 'count': 24}, 'inform...","['Immigrant voices make democracy stronger', '...",1496707200,"06/05/2017, 20:00:00",1505851216,"09/19/2017, 16:00:16",https://www.ted.com/talks/duarte_geraldino_wha...,17,450430,"So, Ma was trying to explain something to me a..."
2459,The most Martian place on Earth,How can you study Mars without a spaceship? He...,Armando Azua-Bustos,Astrobiologist,1,3,4.83,TED2017,"['Mars', 'South America', 'TED Fellows', 'astr...","{'fascinating': {'id': 22, 'count': 32}, 'info...","['Adventures of an asteroid hunter', 'Why Eart...",1492992000,"04/23/2017, 20:00:00",1505919737,"09/20/2017, 11:02:17",https://www.ted.com/talks/armando_azua_bustos_...,6,417470,This is a picture of a sunset on Mars taken by...
2460,What intelligent machines can learn from a sch...,Science fiction visions of the future show us ...,Radhika Nagpal,Robotics engineer,1,1,10.85,TED2017,"['AI', 'ants', 'fish', 'future', 'innovation',...","{'beautiful': {'id': 1, 'count': 14}, 'informa...","['The future of flying robots', 'Meet Spot, th...",1492992000,"04/23/2017, 20:00:00",1506006095,"09/21/2017, 11:01:35",https://www.ted.com/talks/radhika_nagpal_what_...,10,375647,"In my early days as a graduate student, I went..."
2461,A black man goes undercover in the alt-right,In an unmissable talk about race and politics ...,Theo E.J. Wilson,Public intellectual,1,1,18.33,TEDxMileHigh,"['Internet', 'TEDx', 'United States', 'communi...","{'longwinded': {'id': 11, 'count': 3}, 'unconv...","['How barbershops can keep men healthy', 'We n...",1499472000,"07/07/2017, 20:00:00",1506024042,"09/21/2017, 16:00:42",https://www.ted.com/talks/theo_e_j_wilson_a_bl...,32,419309,I took a cell phone and accidentally made myse...
2462,How a video game might help us build better ci...,With more than half of the world population li...,Karoliina Korppoo,Game designer,1,1,8.65,TED2017,"['cities', 'design', 'future', 'infrastructure...","{'unconvincing': {'id': 21, 'count': 21}, 'inf...","['4 ways to make a city more walkable', '7 pri...",1492992000,"04/23/2017, 20:00:00",1506092422,"09/22/2017, 11:00:22",https://www.ted.com/talks/karoliina_korppoo_ho...,8,391721,"We humans are becoming an urban species, so ci..."

<div style="background: #000;
            color: #FFF;
            margin: 0px;
            padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1>Lab</h1>
</div>

For today's lab, we'll be using the Marvel comic book characters data set available from [538](https://github.com/fivethirtyeight/data/tree/master/comic-characters)

The data comes from [Marvel Wikia](http://marvel.wikia.com/Main_Page) and [DC Wikia](http://dc.wikia.com/wiki/Main_Page). Characters were scraped on August 24. Appearance counts were scraped on September 2. The month and year of the first issue each character appeared in was pulled on October 6.

The data is split into two files, for DC and Marvel, respectively: `dc-wikia-data.csv` and `marvel-wikia-data.csv`. Each file has the following variables:

Variable | Definition
---|---------
`page_id` | The unique identifier for that characters page within the wikia
`name` | The name of the character
`urlslug` | The unique url within the wikia that takes you to the character
`ID` | The identity status of the character (Secret Identity, Public identity, [on marvel only: No Dual Identity])
`ALIGN` | If the character is Good, Bad or Neutral
`EYE` | Eye color of the character
`HAIR` | Hair color of the character
`SEX` | Sex of the character (e.g. Male, Female, etc.)
`GSM` | If the character is a gender or sexual minority (e.g. Homosexual characters, bisexual characters)
`ALIVE` | If the character is alive or deceased
`APPEARANCES` | The number of appareances of the character in comic books (as of Sep. 2, 2014. Number will become increasingly out of date as time goes on.)
`FIRST APPEARANCE` | The month and year of the character's first appearance in a comic book, if available
`YEAR` | The year of the character's first appearance in a comic book, if available

Importing the libraries we'll be using

In [2]:
import numpy as np 
import pandas as pd 
import datetime

Let's open the `marvel-wikia-data.csv` file and generate a dataframe. Then we'll check the top of the `df` to see what we have.

In [3]:
df = pd.read_csv("../datasets/marvel-wikia-data.csv")
df.head()

,page_id,name,urlslug,ID,ALIGN,EYE,HAIR,SEX,GSM,ALIVE,APPEARANCES,FIRST APPEARANCE,Year
0,1678,Spider-Man (Peter Parker),\/Spider-Man_(Peter_Parker),Secret Identity,Good Characters,Hazel Eyes,Brown Hair,Male Characters,NaN,Living Characters,4043.0,Aug-62,1962.0
1,7139,Captain America (Steven Rogers),\/Captain_America_(Steven_Rogers),Public Identity,Good Characters,Blue Eyes,White Hair,Male Characters,NaN,Living Characters,3360.0,Mar-41,1941.0
2,64786,"Wolverine (James \""Logan\"" Howlett)",\/Wolverine_(James_%22Logan%22_Howlett),Public Identity,Neutral Characters,Blue Eyes,Black Hair,Male Characters,NaN,Living Characters,3061.0,Oct-74,1974.0
3,1868,"Iron Man (Anthony \""Tony\"" Stark)",\/Iron_Man_(Anthony_%22Tony%22_Stark),Public Identity,Good Characters,Blue Eyes,Black Hair,Male Characters,NaN,Living Characters,2961.0,Mar-63,1963.0
4,2460,Thor (Thor Odinson),\/Thor_(Thor_Odinson),No Dual Identity,Good Characters,Blue Eyes,Blond Hair,Male Characters,NaN,Living Characters,2258.0,Nov-50,1950.0

As you can see we have a couple of issues:
* The column `names` has, in some cases, both the hero name and their secret identity. In other cases, it has the universe the hero is from (usually Earth-616). We'd like for `name` to be the superhero. If a secret identity name is available, we'd like for that to be in it's own column. We'd also like a column `origin` for the superhero's place of origin (usually Earth-616).
* The `urlslug` column is incorrect. We'd like for that to be a complete link. For example, spiderman's wikia link is https://marvel.fandom.com/wiki/Peter_Parker_(Earth-616) but if you use the `Spider-Man_(Peter_Parker)` from the `urlslug` (https://marvel.fandom.com/wiki/Spider-Man_(Peter_Parker), the page redirects to the correct page. You can choose to fix it various different ways but it should be a working link. Use "https://marvel.fandom.com/wiki/" as the beginning of your url.
* For the column `align`, we'd like for the "Characters" part to be removed. We'd like for that column to be categorical (Good, Neutral, Evil or blank).
* Same for the columns `EYE`, `HAIR`, `SEX` and `ID`. We want to drop the extraneous data and have simple categories (e.g. for `ID` we want categories ["Known","Public", "Secret", "None"] and for `SEX` we just want ["Male", "Female","Genderfluid","Agender"]. There's a way shown below that shows the various possible categories.
* Some data is in the wrong format. For example, `Year` and `APPEARANCES` are floats but they really should be ints (as you cannot have a non-int number of appearances). 
* Some data doesn't match up (like the `FIRST APPEARANCE` and `Year` columns might have not be the same year)
* Some columns are unnecessary. Some are missing data. Some rows are duplicates. Fix those as necessary.
* Some column names are written as uppercase, some are lowercase and some are mixed case. Normalize them so all the column names are in the same format.

Fix as many of these issues as you're able to. At the minimum, complete 4 of the above bulletpoints.

In [ ]:
def see_possible_categories(col):
    return df.groupby(col).sum()
    
see_possible_categories('name')